# Generated by Django 5.2.6 on 2025-11-25 19:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_interest_profile_interests"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Без названия",
                        max_length=200,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        default="Без темы", verbose_name="Тема события"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "max_participants",
                    models.PositiveSmallIntegerField(
                        default=1,
                        verbose_name="Максимальное количество участников",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="Не указано",
                        verbose_name="Примерное местоположение, город",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Создано"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025,
                            11,
                            25,
                            22,
                            53,
                            13,
                            798727,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="Истекает через",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="users.user",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events_participating",
                        to="users.user",
                        verbose_name="Участники",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "db_table": "event",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="event_expires_e548bb_idx"
                    ),
                    models.Index(
                        fields=["topic", "is_active"],
                        name="event_topic_36073a_idx",
                    ),
                ],
            },
        ),
    ]
