# Generated by Django 5.2.6 on 2025-12-20 22:20

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("events", "0001_initial"),
        ("events", "0002_event_who_can_see_alter_event_creator_and_more"),
        ("events", "0003_alter_event_expires_at"),
        ("events", "0004_alter_event_expires_at"),
        ("events", "0005_alter_event_expires_at"),
        (
            "events",
            "0002_alter_event_creator_alter_event_description_and_more",
        ),
        ("events", "0006_merge_20251127_1833"),
        ("events", "0007_alter_event_expires_at"),
        ("events", "0008_alter_event_expires_at_eventrequest"),
        ("events", "0009_alter_event_expires_at"),
        ("events", "0010_alter_event_expires_at"),
        ("events", "0011_alter_event_expires_at"),
        ("events", "0012_alter_event_expires_at"),
        ("events", "0013_alter_event_expires_at"),
        ("events", "0014_alter_event_expires_at"),
        ("events", "0015_alter_event_expires_at"),
        ("events", "0016_event_interests_alter_event_expires_at"),
        ("events", "0017_alter_event_expires_at"),
        ("events", "0018_alter_event_expires_at"),
        ("events", "0019_alter_event_expires_at"),
        ("events", "0020_event_latitude_event_longitude_and_more"),
        ("events", "0021_alter_event_expires_at"),
        ("events", "0022_event_image_alter_event_expires_at"),
        ("events", "0023_alter_event_expires_at"),
    ]

    dependencies = [
        ("users", "0002_interest_profile_interests"),
        ("users", "0003_friendship"),
        ("users", "0007_telegramphoneverify_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Без названия",
                        max_length=200,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        default="Без темы", verbose_name="Тема события"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Описание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "max_participants",
                    models.PositiveSmallIntegerField(
                        default=1,
                        verbose_name="Максимальное количество участников",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="Не указано",
                        verbose_name="Примерное местоположение, город",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Создано"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=events.models.default_expires_at,
                        validators=[
                            django.core.validators.MinValueValidator(
                                events.models.min_expires_at
                            )
                        ],
                        verbose_name="Истекает через (не ранее 15мин с этого момента)",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="users.user",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events_participating",
                        to="users.user",
                        verbose_name="Участники",
                    ),
                ),
                (
                    "who_can_see",
                    models.CharField(
                        choices=[
                            ("all", "Все"),
                            ("only_friends", "Только друзья"),
                            ("only_for_me", "Только я"),
                        ],
                        default=("all", "Все"),
                        verbose_name="Кто может видеть публикацию",
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="events",
                        to="users.interest",
                        verbose_name="Интересы",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Широта"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Долгота"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=events.models.Event.get_upload_path,
                        verbose_name="картинка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
                "db_table": "event",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="event_expires_e548bb_idx"
                    ),
                    models.Index(
                        fields=["topic", "is_active"],
                        name="event_topic_36073a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EventRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("accepted", "Принят"),
                            ("rejected", "Отклонен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Сообщение"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="events.event",
                        verbose_name="Событие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_requests",
                        to="users.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос на событие",
                "verbose_name_plural": "Запросы на события",
                "db_table": "event_request",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"),
                        name="unique_constraint_event_user",
                    )
                ],
            },
        ),
    ]
