# Generated by Django 5.2.6 on 2025-11-26 19:27

import datetime
import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("users", "0002_interest_profile_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="who_can_see",
            field=models.CharField(
                choices=[
                    ("all", "Все"),
                    ("only_friends", "Только друзья"),
                    ("only_for_me", "Только я"),
                ],
                default=("all", "Все"),
                verbose_name="Кто может видеть публикацию",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025,
                    11,
                    26,
                    22,
                    27,
                    56,
                    882338,
                    tzinfo=datetime.timezone.utc,
                ),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2025,
                            11,
                            26,
                            19,
                            42,
                            56,
                            882346,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
                verbose_name="Истекает через (не ранее 15мин с этого момента)",
            ),
        ),
    ]
