# Generated by Django 5.2.6 on 2025-11-27 09:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025,
                    11,
                    27,
                    12,
                    35,
                    11,
                    430541,
                    tzinfo=datetime.timezone.utc,
                ),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2025,
                            11,
                            27,
                            9,
                            50,
                            11,
                            430541,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
                verbose_name="Истекает через (не ранее 15мин с этого момента)",
            ),
        ),
    ]
