# Generated by Django 5.2.6 on 2025-11-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0002_alter_event_creator_alter_event_description_and_more",
        ),
        ("events", "0005_alter_event_expires_at"),
    ]

    operations = []
