# Generated by Django 5.2.6 on 2025-11-27 15:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_merge_20251127_1833"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025,
                    11,
                    27,
                    18,
                    33,
                    49,
                    205010,
                    tzinfo=datetime.timezone.utc,
                ),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2025,
                            11,
                            27,
                            15,
                            48,
                            49,
                            205010,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
                verbose_name="Истекает через (не ранее 15мин с этого момента)",
            ),
        ),
    ]
