# Generated by Django 5.2.6 on 2025-11-28 19:49

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_event_expires_at"),
        ("users", "0003_friendship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025,
                    11,
                    28,
                    22,
                    49,
                    51,
                    509969,
                    tzinfo=datetime.timezone.utc,
                ),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2025,
                            11,
                            28,
                            20,
                            4,
                            51,
                            509977,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
                verbose_name="Истекает через (не ранее 15мин с этого момента)",
            ),
        ),
        migrations.CreateModel(
            name="EventRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("accepted", "Принят"),
                            ("rejected", "Отклонен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Сообщение"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="events.event",
                        verbose_name="Событие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_requests",
                        to="users.user",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос на событие",
                "verbose_name_plural": "Запросы на события",
                "db_table": "event_request",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "user"),
                        name="unique_constraint_event_user",
                    )
                ],
            },
        ),
    ]
