# Generated by Django 5.2.6 on 2025-12-10 15:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_alter_event_expires_at"),
        ("users", "0007_telegramphoneverify_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                to="users.interest",
                verbose_name="Интересы",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025,
                    12,
                    10,
                    18,
                    8,
                    5,
                    316975,
                    tzinfo=datetime.timezone.utc,
                ),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2025,
                            12,
                            10,
                            15,
                            23,
                            5,
                            316975,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
                verbose_name="Истекает через (не ранее 15мин с этого момента)",
            ),
        ),
    ]
