# Generated by Django 5.2.6 on 2025-12-13 16:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_alter_event_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Широта"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Долгота"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025,
                    12,
                    13,
                    19,
                    38,
                    32,
                    733062,
                    tzinfo=datetime.timezone.utc,
                ),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2025,
                            12,
                            13,
                            16,
                            53,
                            32,
                            733071,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
                verbose_name="Истекает через (не ранее 15мин с этого момента)",
            ),
        ),
    ]
