# Generated by Django 5.2.6 on 2025-12-13 18:25

import datetime
import django.core.validators
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_alter_event_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=events.models.Event.get_upload_path,
                verbose_name="картинка",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025,
                    12,
                    13,
                    21,
                    25,
                    13,
                    411249,
                    tzinfo=datetime.timezone.utc,
                ),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2025,
                            12,
                            13,
                            18,
                            40,
                            13,
                            411249,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
                verbose_name="Истекает через (не ранее 15мин с этого момента)",
            ),
        ),
    ]
