# Generated by Django 5.2.6 on 2025-12-16 13:43

import django.core.validators
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_event_image_alter_event_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="expires_at",
            field=models.DateTimeField(
                default=events.models.default_expires_at,
                validators=[
                    django.core.validators.MinValueValidator(
                        events.models.min_expires_at
                    )
                ],
                verbose_name="Истекает через (не ранее 15мин с этого момента)",
            ),
        ),
    ]
