# Generated by Django 5.2.6 on 2025-11-29 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="telegram_id"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tg_last_message_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tg_messages_cnt",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                validators=[django.core.validators.MaxValueValidator(10)],
                verbose_name="Количество сообщений",
            ),
        ),
    ]
