# Generated by Django 5.2.6 on 2025-12-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0004_profile_telegram_id_profile_tg_last_message_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="code",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="code"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telephone",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="telephone"
            ),
        ),
    ]
