# Generated by Django 5.2.6 on 2025-12-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_code_profile_telephone"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramPhoneVerify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="telegram_id"
                    ),
                ),
                (
                    "telephone",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="telephone"
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="code"
                    ),
                ),
            ],
            options={
                "verbose_name": "TelegramPhoneVerify",
                "verbose_name_plural": "TelegramPhoneVerifies",
            },
        ),
    ]
