# Generated by Django 5.2.6 on 2025-12-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_telegramphoneverify"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramphoneverify",
            name="username",
            field=models.CharField(
                blank=True, null=True, verbose_name="username"
            ),
        ),
    ]
