# Generated by Django 5.2.6 on 2025-12-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_activationtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activationtoken",
            name="is_used",
        ),
    ]
