# Generated by Django 5.2.6 on 2025-12-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_activationtoken_is_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="code",
        ),
    ]
