# Generated by Django 5.2.6 on 2025-12-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_profile_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelegramPhoneVerify",
        ),
    ]
