# Generated by Django 5.2.6 on 2025-12-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_delete_telegramphoneverify"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                fields=("from_user", "to_user"), name="unique_friendship"
            ),
        ),
    ]
